list =["IT",6,9,"IT","department"]
list2 =[45,78,4]
print(list)
list.append(70)
print(list)
list.extend([12,"SYSS"])
print(list)
list.insert(3,"roshan")
print(list)
list.remove(6)
print(list)
list.pop(5)
print(list)
print(list[2:6])
list.reverse()
print(list)
print(len(list))
print(min([6,9]))
print(max([6,9]))
print(list.count("IT"))
print(list + list2)
print(list * 2)
print(list.index(9))
list2.sort()
print(list)
list.clear()
print(list)
